# object_info.py

object_info = {
    "Messier 1": ("Crab Nebula", "6,500 ly"),
    "Messier 2": ("Globular Cluster in Aquarius", "37,500 ly"),
    "Messier 3": ("Globular Cluster in Canes Venatici", "33,900 ly"),
    "Messier 4": ("Globular Cluster in Scorpius", "7,200 ly"),
    "Messier 5": ("Globular Cluster in Serpens", "24,500 ly"),
    "Messier 6": ("Butterfly Cluster", "1,600 ly"),
    "Messier 7": ("Ptolemy Cluster", "980 ly"),
    "Messier 8": ("Lagoon Nebula", "4,100 ly"),
    "Messier 9": ("Globular Cluster in Ophiuchus", "25,800 ly"),
    "Messier 10": ("Globular Cluster in Ophiuchus", "14,300 ly"),
    "Messier 11": ("Wild Duck Cluster", "6,200 ly"),
    "Messier 12": ("Globular Cluster in Ophiuchus", "16,000 ly"),
    "Messier 13": ("Hercules Globular Cluster", "22,200 ly"),
    "Messier 14": ("Globular Cluster in Ophiuchus", "30,300 ly"),
    "Messier 15": ("Globular Cluster in Pegasus", "33,600 ly"),
    "Messier 16": ("Eagle Nebula", "7,000 ly"),
    "Messier 17": ("Omega Nebula (Swan)", "5,500 ly"),
    "Messier 18": ("Open Cluster in Sagittarius", "4,900 ly"),
    "Messier 19": ("Globular Cluster in Ophiuchus", "28,500 ly"),
    "Messier 20": ("Trifid Nebula", "5,200 ly"),
    "Messier 21": ("Open Cluster in Sagittarius", "4,250 ly"),
    "Messier 22": ("Globular Cluster in Sagittarius", "10,400 ly"),
    "Messier 23": ("Open Cluster in Sagittarius", "2,150 ly"),
    "Messier 24": ("Sagittarius Star Cloud", "10,000 ly"),
    "Messier 25": ("Open Cluster in Sagittarius", "2,000 ly"),
    "Messier 26": ("Open Cluster in Scutum", "5,000 ly"),
    "Messier 27": ("Dumbbell Nebula", "1,360 ly"),
    "Messier 28": ("Globular Cluster in Sagittarius", "18,000 ly"),
    "Messier 29": ("Open Cluster in Cygnus", "4,000 ly"),
    "Messier 30": ("Globular Cluster in Capricornus", "26,000 ly"),
    "Messier 31": ("Andromeda Galaxy", "2.5 million ly"),
    "Messier 32": ("Dwarf Elliptical Galaxy in Andromeda", "2.5 million ly"),
    "Messier 33": ("Triangulum Galaxy", "2.7 million ly"),
    "Messier 34": ("Open Cluster in Perseus", "1,400 ly"),
    "Messier 35": ("Open Cluster in Gemini", "2,800 ly"),
    "Messier 36": ("Open Cluster in Auriga", "4,100 ly"),
    "Messier 37": ("Open Cluster in Auriga", "4,500 ly"),
    "Messier 38": ("Open Cluster in Auriga", "4,200 ly"),
    "Messier 39": ("Open Cluster in Cygnus", "825 ly"),
    "Messier 40": ("Double Star in Ursa Major", "510 ly"),
    "Messier 41": ("Open Cluster in Canis Major", "2,300 ly"),
    "Messier 42": ("Orion Nebula", "1,344 ly"),
    "Messier 43": ("De Mairan's Nebula", "1,344 ly"),
    "Messier 44": ("Beehive Cluster", "577 ly"),
    "Messier 45": ("Pleiades", "444 ly"),
    "Messier 46": ("Open Cluster in Puppis", "5,400 ly"),
    "Messier 47": ("Open Cluster in Puppis", "1,600 ly"),
    "Messier 48": ("Open Cluster in Hydra", "1,500 ly"),
    "Messier 49": ("Elliptical Galaxy in Virgo", "56 million ly"),
    "Messier 50": ("Open Cluster in Monoceros", "3,000 ly"),
    "Messier 51": ("Whirlpool Galaxy", "23 million ly"),
    "Messier 52": ("Open Cluster in Cassiopeia", "5,000 ly"),
    "Messier 53": ("Globular Cluster in Coma Berenices", "58,000 ly"),
    "Messier 54": ("Globular Cluster in Sagittarius", "87,000 ly"),
    "Messier 55": ("Globular Cluster in Sagittarius", "17,600 ly"),
    "Messier 56": ("Globular Cluster in Lyra", "32,900 ly"),
    "Messier 57": ("Ring Nebula", "2,300 ly"),
    "Messier 58": ("Barred Spiral Galaxy in Virgo", "62 million ly"),
    "Messier 59": ("Elliptical Galaxy in Virgo", "60 million ly"),
    "Messier 60": ("Elliptical Galaxy in Virgo", "55 million ly"),
    "Messier 61": ("Spiral Galaxy in Virgo", "52 million ly"),
    "Messier 62": ("Globular Cluster in Ophiuchus", "22,500 ly"),
    "Messier 63": ("Sunflower Galaxy", "27 million ly"),
    "Messier 64": ("Black Eye Galaxy", "17 million ly"),
    "Messier 65": ("Spiral Galaxy in Leo", "35 million ly"),
    "Messier 66": ("Spiral Galaxy in Leo", "36 million ly"),
    "Messier 67": ("Open Cluster in Cancer", "2,700 ly"),
    "Messier 68": ("Globular Cluster in Hydra", "33,000 ly"),
    "Messier 69": ("Globular Cluster in Sagittarius", "29,700 ly"),
    "Messier 70": ("Globular Cluster in Sagittarius", "29,400 ly"),
    "Messier 71": ("Globular Cluster in Sagitta", "13,000 ly"),
    "Messier 72": ("Globular Cluster in Aquarius", "55,000 ly"),
    "Messier 73": ("Asterism in Aquarius", "2,500 ly"),
    "Messier 74": ("Spiral Galaxy in Pisces", "32 million ly"),
    "Messier 75": ("Globular Cluster in Sagittarius", "67,500 ly"),
    "Messier 76": ("Little Dumbbell Nebula", "2,500 ly"),
    "Messier 77": ("Barred Spiral Galaxy in Cetus", "47 million ly"),
    "Messier 78": ("Reflection Nebula in Orion", "1,350 ly"),
    "Messier 79": ("Globular Cluster in Lepus", "42,000 ly"),
    "Messier 80": ("Globular Cluster in Scorpius", "32,600 ly"),
    "Messier 81": ("Bode's Galaxy", "12 million ly"),
    "Messier 82": ("Cigar Galaxy", "12 million ly"),
    "Messier 83": ("Southern Pinwheel Galaxy", "15 million ly"),
    "Messier 84": ("Elliptical Galaxy in Virgo", "60 million ly"),
    "Messier 85": ("Lenticular Galaxy in Coma Berenices", "60 million ly"),
    "Messier 86": ("Lenticular Galaxy in Virgo", "52 million ly"),
    "Messier 87": ("Supergiant Elliptical Galaxy (Virgo A)", "53 million ly"),
    "Messier 88": ("Spiral Galaxy in Coma Berenices", "47 million ly"),
    "Messier 89": ("Elliptical Galaxy in Virgo", "50 million ly"),
    "Messier 90": ("Spiral Galaxy in Virgo", "58 million ly"),
    "Messier 91": ("Barred Spiral Galaxy in Coma Berenices", "63 million ly"),
    "Messier 92": ("Globular Cluster in Hercules", "26,700 ly"),
    "Messier 93": ("Open Cluster in Puppis", "3,600 ly"),
    "Messier 94": ("Spiral Galaxy in Canes Venatici", "16 million ly"),
    "Messier 95": ("Barred Spiral Galaxy in Leo", "38 million ly"),
    "Messier 96": ("Spiral Galaxy in Leo", "31 million ly"),
    "Messier 97": ("Owl Nebula", "2,600 ly"),
    "Messier 98": ("Spiral Galaxy in Coma Berenices", "44 million ly"),
    "Messier 99": ("Spiral Galaxy in Coma Berenices", "45 million ly"),
    "Messier 100": ("Barred Spiral Galaxy in Coma Berenices", "55 million ly"),
    "Messier 101": ("Pinwheel Galaxy", "21 million ly"),
    "Messier 102": ("Possibly Spindle Galaxy", "60 million ly"),
    "Messier 103": ("Open Cluster in Cassiopeia", "10,000 ly"),
    "Messier 104": ("Sombrero Galaxy", "29.3 million ly"),
    "Messier 105": ("Elliptical Galaxy in Leo", "32 million ly"),
    "Messier 106": ("Spiral Galaxy in Canes Venatici", "25 million ly"),
    "Messier 107": ("Globular Cluster in Ophiuchus", "20,900 ly"),
    "Messier 108": ("Spiral Galaxy in Ursa Major", "46 million ly"),
    "Messier 109": ("Barred Spiral Galaxy in Ursa Major", "83 million ly"),
    "Messier 110": ("Dwarf Elliptical Galaxy near Andromeda", "2.7 million ly"),
    "NGC 869": ("Double Cluster in Perseus (h Persei)", "7,500 ly"),
    "NGC 884": ("Double Cluster in Perseus (χ Persei)", "7,500 ly"),
    "NGC 253": ("Sculptor Galaxy", "11.4 million ly"),
    "NGC 281": ("Pacman Nebula", "9,500 ly"),
    "NGC 891": ("Edge-on Spiral Galaxy in Andromeda", "30 million ly"),
    "NGC 2244": ("Rosette Nebula Cluster", "5,200 ly"),
    "NGC 2392": ("Eskimo Nebula", "2,870 ly"),
    "NGC 2903": ("Spiral Galaxy in Leo", "30 million ly"),
    "NGC 3132": ("Eight-Burst Nebula (Southern Ring Nebula)", "2,000 ly"),
    "NGC 3372": ("Carina Nebula", "8,500 ly"),
    "NGC 3628": ("Hamburger Galaxy", "35 million ly"),
    "NGC 4038": ("Antennae Galaxies (part)", "45 million ly"),
    "NGC 4039": ("Antennae Galaxies (part)", "45 million ly"),
    "NGC 4565": ("Needle Galaxy", "30–50 million ly"),
    "NGC 457": ("Owl Cluster (ET Cluster)", "7,900 ly"),
    "NGC 5128": ("Centaurus A", "10–16 million ly"),
    "NGC 5907": ("Splinter Galaxy", "53 million ly"),
    "NGC 6960": ("Veil Nebula (Western - Witch's Broom)", "1,470 ly"),
    "NGC 6992": ("Veil Nebula (Eastern)", "1,470 ly"),
    "NGC 7000": ("North America Nebula", "2,590 ly"),
    "NGC 7023": ("Iris Nebula", "1,300 ly"),
    "NGC 7293": ("Helix Nebula", "650 ly"),
}
